[options]
db_user = odoo
db_password = odoo
http_port = 17000
db_name = o17-0501
without_demo = all
# server_wide_modules = web,openupgrade_framework
addons_path = ~/loym/conf/CX17/cetmix/cetmix-tower,
              ~/loym/conf/CX17/loymcom/apps
              
#                 ~/loym/conf/CX17/.venv/lib/python3.12/site-packages/odoo/addons
