# we use the hatch-odoo build backend which knows how to detect dependencies
# from Odoo addons manifests
[build-system]
requires = ["hatchling", "hatch-odoo"]
build-backend = "hatchling.build"

[project]
name = "19e"
version = "0.1.0"
description = "Based on OCA Days 2024 Odoo demo with uv-level9"
readme = "README.md"
requires-python = "==3.12.*"
dynamic = ["dependencies"]

# tell uv when dependencies may change
[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "addons/dependencies/__manifest__.py" },
]

[tool.hatch.build]
packages = ["odoo"]

# Enable the hatch-odoo metadata hook to generate dependencies from addons manifests.
[tool.hatch.metadata.hooks.odoo-addons-dependencies]

[tool.hatch-odoo]
# dependencies that are not in the addons manifest
dependencies = [
    "odoo==19.0.*",
    # Add some constraints to Odoo deps that should be in their setup.py
    "lxml[html_clean]>=5.2",
    "setuptools<71",
    "werkzeug==3.0.*",
    "click-odoo-contrib",
    # "git+https://github.com/acsone/click-odoo-contrib.git@master#egg=click-odoo-contrib",

    # odoo/community
    "asn1crypto",
    "cryptography",
    "geoip2",
    # ldap -> python-ldap
    "pdfminer",
    "phonenumbers",
    "pyOpenSSL",
    "pyserial",
    "python-ldap",
    "pyusb",
    "qrcode",

    # odoo/enterprise
    "cryptography",
    "dbfread",
    "google_auth",
    "pyjwt",
    "xmlsec", # error
    "zeep",
    "PyPDF2<3.0.0",
]
addons_dirs = ["addons"]

[tool.uv.sources]
odoo = { git = "https://github.com/OCA/OCB", branch = "19.0" }

odoo-addon-project_parent = { git = "https://github.com/norlinhenrik/oca-project", branch = "19.0-mig-project_parent", subdirectory = "project_parent" }
