
{
    "name": "Dependencies",
    "author": "Loym",
    "depends": [
        "account_partner_company_group",
        "auth_admin_passkey",
        "base_location",
        "base_location_geonames_import",
        "base_partner_company_group",
        "base_partner_sequence",
        "crm_partner_company_group",
        "dbfilter_from_header",
        "document_page_quality_manual",
        "document_page_approval",
        "document_page_procedure",
        "document_page_environment_manual",
        "document_page_work_instruction",
        # "partner_contact_sale_info_propagation", # 1:33
        "partner_industry_secondary",
        "product_pricelist_supplierinfo",
        "product_sequence",
        "product_state",
        "project_parent",
        "project_role",
        "project_sequence",
        "project_task_default_stage",
        "project_type",
        "sale_order_line_menu",
        "sale_partner_company_group",
        "sale_partner_selectable_option",
        "web_notify",
    ],
    "version": "18.0.1.0.0",
}
